<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class AgentSpecificationController extends Controller
{
    public function show(Request $request): Response
    {
        $agent = $request->user();
        $abilities = collect($agent->currentAccessToken()?->abilities ?? [])->sort()->values();
        $memberships = $agent->scopeMemberships()
            ->where('is_active', true)
            ->with('scope:id,name,slug')
            ->orderBy('scope_id')
            ->get();
        $language = match ($agent->preferred_language) {
            'en' => ['English', 'Write task comments, durable notes, reports, and user-facing answers in English unless the task explicitly requires another language.'],
            'zh' => ['Chinese', 'Write task comments, durable notes, reports, and user-facing answers in Chinese unless the task explicitly requires another language.'],
            default => ['Russian', 'Write task comments, durable notes, reports, and user-facing answers in Russian unless the task explicitly requires another language.'],
        };

        $scopeLines = $memberships->map(function ($membership): string {
            $scope = $membership->scope;

            return sprintf(
                '- `%s` — %s; role `%s`; project access `%s`',
                $scope->id,
                $scope->name,
                $membership->role,
                $membership->project_access_mode,
            );
        });

        $lines = [
            '# Zuratax Agent API',
            '',
            'Specification version: 2026-09-29.1',
            'Generated at: '.now()->toIso8601String(),
            '',
            '## Identity and access',
            '',
            "You are authenticated as **{$agent->name}** (`{$agent->id}`).",
            "Working language: **{$language[0]}** (`{$agent->preferred_language}`).",
            $language[1],
            'Token abilities: '.($abilities->isEmpty() ? '_none_' : $abilities->map(fn (string $ability): string => "`{$ability}`")->implode(', ')).'.',
            '',
            'Accessible scopes:',
            ...($scopeLines->isEmpty() ? ['- _none_'] : $scopeLines->all()),
            '',
            '## Transport contract',
            '',
            '- Use HTTPS and send the token only as `Authorization: Bearer <token>`.',
            '- Send `Accept: application/json` for API data and `Content-Type: application/json` for POST/PATCH requests, except Filer uploads: use multipart/form-data and let your HTTP library generate the boundary.',
            '- Never put the token in a URL, task text, comment, log, commit, or chat message.',
            '- Treat `401` as an invalid/revoked token, `403` as a scope/capability boundary, and `422` as a validation error.',
            '- Follow pagination links/meta where a collection is paginated.',
            '- Use task keys such as `ADM-154` when talking to people; use entity IDs in API paths and payloads.',
            '',
            '## Discovery and work queue',
            '',
            '- `GET /api/agent/spec` — fetch this current specification before starting work.',
            '- `GET /api/agent/me` — verify the account.',
            '- `GET /api/agent/scopes` — list accessible scopes.',
            '- `GET /api/agent/tasks` — personal delegated queue. Add `?include_closed=1` to include done and cancelled tasks.',
            '',
            'The personal queue only contains tasks explicitly delegated to this agent and marked as agent-delegatable. Do not infer access from a task mentioned elsewhere.',
            '',
            '## Filer API',
            '',
            'File metadata includes optional plain-text description. PATCH /api/agent/scopes/{scope}/files/{file} accepts only {description: string|null} (maximum 2000 characters); requires task.update plus file management access. Upload does not require a description.',
            'Office preview: POST /api/agent/scopes/{scope}/files/{file}/preview queues a PDF copy (read permission suffices); GET on the same URL polls {data:{status}} (idle, pending, ready, failed, unavailable, unsupported). Poll at most once per 3 seconds, stop after 2 minutes and report pending instead of retrying forever. GET /api/agent/scopes/{scope}/files/{file}/preview/content downloads the ready PDF with the same ACL as the original. On failed, retry only explicitly. This does not edit the original. Word/Excel/ODF conversion is local, no third-party upload.',
            '',
            'Base path: `/api/agent/scopes/{scope}/files`. Requires active scope membership and `task.view` in both account permissions and token abilities. Existing subject/project/book privacy checks always apply.',
            '- `GET /`: list readable files; filters `category`, `q`, `subject_type` + `subject_id`, `page`. Response `{data: [...], meta: {page, has_more}}`, up to 30 per page.',
            '- `GET /targets?type=task&q=...`: up to 50 writable attachment targets; requires `task.update`. Types: task, event, book, project, user.',
            '- `POST /`: upload multipart fields `file` (maximum 20 MiB), `category`, `visibility` (private or scope), optional `subject_type` and `subject_id`. Categories: documentation, general, task, event, book, project, user. Module categories require a matching target. Requires `task.update` and write access to the target (including `book.update` for books). Returns 201 with `{data: file}`.',
            '- `GET /{file}/download`: binary attachment, not JSON. Keep the Bearer key in the header, never the URL.',
            '- `POST /{file}/attachments`: JSON `subject_type`, `subject_id`; requires `task.update`, ownership (or scope owner), and write access to every existing and new target.',
            '- `DELETE /{file}`: permanently removes physical content and ALL attachment links; requires `task.update`, `task.delete`, ownership (or scope owner), and write access to every target. Returns 204. Only delete when explicitly authorized by the user.',
            '- Private files are author-only, even for scope owners. Scope files require access to ALL linked subjects; linking to a public task does not expose a private book attachment. `can_manage` describes ownership/subject write access; route token abilities are required additionally.',
            '- 401: revoked/invalid key; 403: insufficient permission; 404: absent or inaccessible file/target; 413/422: invalid or oversized upload; 507: insufficient disk space. Do not retry forbidden operations or disk-full uploads blindly.',
            '',
            '## Photos and image attachments',
            '',
            '- Work with files/photos only as needed for the user-assigned task. Do not send private attachments to third-party conversion or analysis services without permission.',
            '- Use the Filer endpoints above. Add `photos=1` to the file list to select JPEG/PNG/WebP images, combined with subject filters when needed.',
            '- Upload multipart `photo=1` with a JPEG, PNG, or WebP file (20 MiB and 24 megapixels maximum). The server corrects JPEG orientation and stores a compressed WebP with a maximum dimension of 2000 px (512 px for user photos), without upscaling. The original is NOT retained. Omit `photo` to preserve the original as a regular file.',
            '- `GET /api/agent/scopes/{scope}/files/{file}/image`: binary inline raster image, not JSON; requires `task.view` and file access. Authenticate with the Bearer header. Use `/download` for original file attachments; neither endpoint is a public URL.',
            '- Attach photos to tasks, events, books, projects, or users using `subject_type` and `subject_id`. For event galleries upload each image separately. Discover writable targets through `/files/targets?type=event` (or another supported type).',
            '- `POST /api/agent/scopes/{scope}/files/{file}/feature`: JSON `{ "subject_type": "event", "subject_id": "<event-ulid>", "enabled": true }` selects an event cover. Use `subject_type=user` for an avatar. `enabled=false` clears the target cover/avatar. Returns 204.',
            '- Selecting a cover/avatar requires `task.update`, read access to the file and write access to the target. The raster photo must have `visibility=scope` and already be attached to that target. An avatar must be a dedicated photo with exactly one attachment. Managing another user additionally requires the appropriate contractor management permission.',
            '- A selected scope-visible avatar can be read through `/image` by colleagues in that scope. This does not make other profile attachments readable and does not grant `/download` access.',
            '- A Booker photo block has type `photo` and payload `{ "scope_id": "<scope-ulid>", "file_id": "<file-ulid>", "caption": "Optional caption" }`. Upload to the book first; normal book access and editing-lock rules still apply when editing blocks. Store file IDs, not Bearer URLs or base64. Physical file deletion can break references in old book versions.',
            '- Booker editing workflow: `POST /api/agent/scopes/{scope}/books/{book}/pages/{page}/editing` acquires the lock (423 means another editor owns it). Create a block via POST to `/blocks`; update an existing block via POST to `/blocks/{group}/versions`. When done, DELETE `/editing` releases the lock. Do not call POST `/editing/cancel` unless explicitly asked to roll back the whole editing session.',
            '',
            '## Planner: monthly plan items (not calendar tails)',
            '',
            'Base path: `/api/agent/scopes/{scope}/plans`. Reads require BOTH `report.view` and `task.view`; writes additionally require BOTH `report.write` and `task.update`, in token abilities and account permissions. Project restrictions and private-project visibility apply. Existing keys do not acquire missing abilities automatically; ask the owner to issue an appropriately scoped key.',
            '- `GET /?year=2026`: year is required (2000–2099); optional `month=2026-10`, `project_id`, `assignee_id`, `status=open|done`, `q`, `page`. Returns `{data:{items:[],total,done,page,last_page}}`, 40 items per page. Fetch subsequent pages through `last_page`.',
            '- `GET /options`: returns `{data:{projects:[],people:[]}}` for accessible projects and scoped real/virtual executors. Assignee access to the chosen project is revalidated on save.',
            '- `GET /candidates?project_id=<project-ulid>&q=...`: selectable tasks, 30 per page, with standard `data`, `links`, `meta` pagination. Omit `project_id` for unprojected tasks, not all projects. Each task includes `linked_plans` with accessible plan IDs, titles, and months; reuse in multiple plans is allowed.',
            '- `GET /{planItem}`: one accessible plan under `data`, with tasks, `tasks_count`, `completed_tasks_count`, project, assignee, and completion information.',
            '- `POST /`: required `title` (max 255) and `month` (`YYYY-MM`, 2000–2099). Optional nullable `project_id`, `assignee_id`, `description` (max 20000), `resources`, `expected_result`, `impact`, `actual_result` (each max 10000), `starts_on`, `ends_on` (`YYYY-MM-DD`), `estimated_minutes` (0–525600); optional `priority` (1–5), `completed` (boolean), `task_ids` (up to 500 distinct task ULIDs), `task_dates` (object mapping task ULIDs to YYYY-MM-DD calendar dates). Each linked task must have a main calendar date in the plan month; provide task_dates to schedule or reschedule it atomically. Returns 200 with `{data: plan}`.',
            '- `PATCH /{planItem}`: same editable fields; omitted fields are preserved. `task_ids` replaces the entire task selection; `[]` clears it. Tasks must be accessible and belong to the same scope and project as the plan. For a project change, explicitly remove or replace old task links in the same request. Dates must be ordered.',
            '- Completion is explicit: PATCH `{ "completed": true, "actual_result": "Verified outcome" }`; `{ "completed": false }` reopens. A plan can be completed without linked tasks. This does NOT complete tasks, create calendar entries, or move calendar tails.',
            '- `DELETE /{planItem}`: soft-delete the plan only, preserving tasks; returns 204. Only call when explicitly authorized by the user.',
            '- Requests leave agent API audit traces; plan changes also record domain history. Plan writes and photo/file operations are limited to 60 requests per minute per group; respect 429 and Retry-After.',
            '',
            'Minimal plan example (POST to the plans base path):',
            '```json',
            '{"title":"Improve reservation workflow","month":"2026-10","project_id":"<project-ulid>","expected_result":"Verified reservation scenarios","task_ids":["<task-ulid>"],"task_dates":{"<task-ulid>":"2026-10-15"}}',
            '```',
            '',
            '## Scope task API',
            '',
            'Replace `{scope}` and `{task}` with IDs returned by the API:',
            '',
            '- `GET /api/agent/scopes/{scope}/projects`',
            '- `POST /api/agent/scopes/{scope}/projects`',
            '- `GET /api/agent/scopes/{scope}/projects/{project}`',
            '- `PATCH /api/agent/scopes/{scope}/projects/{project}`',
            '- `GET /api/agent/scopes/{scope}/books` — list books allowed by `book_access_mode` and project access.',
            '- `POST /api/agent/scopes/{scope}/books` — create a book when `book.create` is allowed.',
            '- `GET /api/agent/scopes/{scope}/books/{book}`',
            '- `PATCH /api/agent/scopes/{scope}/books/{book}` — update when `book.update` is allowed.',
            '- `DELETE /api/agent/scopes/{scope}/books/{book}` — delete when `book.delete` is explicitly allowed.',
            '- `GET|POST /api/agent/scopes/{scope}/books/{book}/pages`',
            '- `GET|PATCH /api/agent/scopes/{scope}/books/{book}/pages/{page}`',
            '- `GET|POST /api/agent/scopes/{scope}/books/{book}/pages/{page}/blocks`',
            '- `GET|POST /api/agent/scopes/{scope}/books/{book}/pages/{page}/comments`',
            '- `GET /api/agent/scopes/{scope}/contractors/assignable` — safe assignee options.',
            '- `POST /api/agent/scopes/{scope}/facts` — create a Factor fact.',
            '- `GET /api/agent/scopes/{scope}/lore/context` — compact current project memory, ordered for agents. Use `?project_id=...` and optional `?as_of=...`.',
            '- `GET /api/agent/scopes/{scope}/lore` — searchable Lore records; filters include `q`, `project_id`, `area_id`, `tag`, `type`, `importance`, `criticality`, and `as_of`.',
            '- `GET /api/agent/scopes/{scope}/lore/{entry}` — one record with its complete immutable revision timeline.',
            '- `POST /api/agent/scopes/{scope}/lore` — create a Lore chain; requires `task.update`.',
            '- Minimal Lore creation payload: `code`, `title`, and Markdown `content`. The API defaults `type=decision`, `importance=mechanic`, `criticality=informational`, `visibility=scope`, and `status=active` when they are omitted.',
            '- `project_id` must be the project ULID returned by the projects endpoint, not its short key. Optional `tags` must be an array of strings.',
            '- `PATCH /api/agent/scopes/{scope}/lore/{entry}` — update Lore metadata. It also accepts `title`, Markdown `content`, and `reason` as a convenient way to edit the currently effective revision in place without finding its revision ID.',
            '- `POST /api/agent/scopes/{scope}/lore/{entry}/revisions` — publish a semantic revision instead of overwriting an earlier decision. Minimal payload is Markdown `content`; omitted `title` is inherited from the current revision and omitted `status` defaults to `active`.',
            '- `PATCH /api/agent/scopes/{scope}/lore/{entry}/revisions/{revision}` — correct the currently effective revision without changing its meaning; only `title`, `content`, and `reason` are editorially mutable.',
            '- `DELETE /api/agent/scopes/{scope}/lore/{entry}` — soft-delete a Lore chain only when `task.delete` is explicitly allowed.',
            '- Lore revision `content` and `reason` are Markdown. Preserve headings, lists, tables, task lists, links, and fenced code blocks; do not flatten them to plain text.',
            '',
            'Minimal Lore create example:',
            '',
            '```json',
            '{"code":"WMS-RESERVE","project_id":"<project-ulid>","title":"Reservation rule","content":"# Rule\\n\\nAvailable quantity excludes reservations.","tags":["wms","reservation"]}',
            '```',
            '',
            'Edit the current revision in place:',
            '',
            '```json',
            '{"content":"# Corrected wording\\n\\nThe meaning is unchanged.","reason":"Editorial correction"}',
            '```',
            '',
            'Publish the next semantic revision:',
            '',
            '```json',
            '{"content":"# New decision\\n\\nThis replaces the earlier rule.","reason":"The business process changed"}',
            '```',
            '',
            'Treat HTTP `422` as payload validation, not throttling: read the JSON `errors` object, fix the named fields, and retry once. Rate limiting is reported only as HTTP `429`.',
            '- `POST /api/agent/scopes/{scope}/links` — link two accessible entities.',
            '- `POST /api/agent/scopes/{scope}/imports/tasker` — idempotent Tasker import; send `dry_run: true` first.',
            '- `POST /api/agent/scopes/{scope}/imports/booker` — idempotent full-book import preserving pages, block types, and block versions; send one book per request and use `dry_run: true` first.',
            '- `GET /api/agent/scopes/{scope}/tasks`',
            '- `POST /api/agent/scopes/{scope}/tasks`',
            '- `GET /api/agent/scopes/{scope}/tasks/search`',
            '- `GET /api/agent/scopes/{scope}/tasks/{task}`',
            '- `PATCH /api/agent/scopes/{scope}/tasks/{task}`',
            '- `GET /api/agent/scopes/{scope}/tasks/{task}/checklist`',
            '- `POST /api/agent/scopes/{scope}/tasks/{task}/checklist`',
            '- `PATCH /api/agent/scopes/{scope}/tasks/{task}/checklist/{item}`',
            '- `GET /api/agent/scopes/{scope}/tasks/{task}/comments`',
            '- `POST /api/agent/scopes/{scope}/tasks/{task}/comments`',
            '- `DELETE /api/agent/scopes/{scope}/tasks/{task}/comments/{comment}`',
            '- `GET /api/agent/scopes/{scope}/tasks/{task}/activity`',
            '',
            '## Task documents',
            '',
            '- `description` — Markdown describing the task, its context, requirements, and constraints.',
            '- `result` — Markdown describing the verified result of completed work.',
            '- `agent_notes` — Markdown for durable AI findings, important answers, investigation notes, and handoff context. It is a separate task document, not a chat transcript.',
            '- `agent_notes` is accepted by task POST/PATCH endpoints. Send `null` to clear it.',
            '- Keep operational progress, questions, and blockers in task comments. Promote only durable information that should remain visible in the full task editor to `agent_notes`.',
            '',
            'Example:',
            '',
            '```json',
            '{"agent_notes":"## Investigation\\n\\nThe API is healthy. Verified with the production smoke test."}',
            '```',
            '',
            'Only call endpoints allowed by both the token abilities and the membership capabilities. Project restrictions remain in force inside a scope.',
            'Load Lore context before substantial project work. Treat foundational and critical records as mandatory constraints. By default use `current_revision`; request history or `as_of` only when investigating an earlier state. Never rewrite a published semantic decision: create a new revision with its effective date and reason.',
            'Book routes additionally enforce `book_access_mode`: `none`, `projects`, or `all`. Never assume that `book.*` token abilities alone grant access to a book.',
            'Creating facts requires `task.create`; creating links requires `task.update`. A link payload contains `source_type`, `source_id`, `target_type`, `target_id`, and optional `relation`, `note`, and `meta`.',
            'Tasker imports require both `task.create` and `task.update`, preserve external ULIDs for idempotency, never delete records, and require all-project access when creating projects.',
            'Booker imports require both `book.create` and `book.update`, full book access in the scope, and preserve external ULIDs. They never delete or overwrite an earlier imported entity.',
            '',
            '## Operating rules',
            '',
            '1. Fetch this specification, verify `/api/agent/me`, then load `/api/agent/tasks`.',
            '2. Read the task, its comments and activity before changing it.',
            '3. Make the smallest necessary change and preserve user data.',
            '4. Record meaningful progress or blockers in a task comment. Never claim completion without verification.',
            '5. If access is missing, stop at the boundary and report the exact endpoint and status; do not attempt to bypass it.',
            '6. Do not perform destructive actions unless the assigned task explicitly authorizes them.',
            '',
            'This endpoint is the source of truth. Fetch it again when a workflow or endpoint behaves differently from a cached instruction.',
        ];

        return response(implode("\n", $lines)."\n", 200, [
            'Content-Type' => 'text/markdown; charset=UTF-8',
            'Cache-Control' => 'no-store, private',
        ]);
    }
}
